### ISSUE TITLE
What is the best way for communication b/w modules?

### ISSUE THREAD

**Issue by chika-kasymov** [abdullahselek/ViperC#1]
For example, I created a new module using **Router** class method `createModule` and pushed returned `UIViewController` to the navigation stack. Then how I'll pass the result of this module back to origin/parent?

I think there should be some protocol for module/wireframe output results.

**Comment by abdullahselek** [comment]
Hi @chika-kasymov, ViperC is the template which is used to setup the initial module. You can always add new protocols and functions in order to your requirements.

**Comment by chika-kasymov** [comment]
Ok, thank you for your response! I just wanted to be sure that I didn't miss similar feature if it already existed in ViperC.
